// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvsxibnxezarozhldbxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2c3hpYm54ZXphcm96aGxkYnhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzOTgyMjUsImV4cCI6MjA1ODk3NDIyNX0.5RAPTwbggYPfJm8F7TH0vA9kbOCJ0uHkudvAEHMvhCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);